<a href="https://colab.research.google.com/github/hzuika/colab/blob/main/index_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([
  [1,2],
  [3,4]
])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0][1] 

2

In [ ]:
a[0,1]

2

In [ ]:
a[(0,1)]

2

In [ ]:
a[tuple([0,1])]

2

In [ ]:
a[tuple(np.array([0,1]))]

2

In [ ]:
a[np.array([0,1])]

array([[1, 2],
       [3, 4]])

In [ ]:
a[[0,1]]

array([[1, 2],
       [3, 4]])